# Example of uses

First we import the module

In [1]:
print("loading the module")

import twitter_profile_predictor as tpp

loading the module

[nltk_data] Downloading package punkt to /home/tim0/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /home/tim0/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

## Method 1 : ``bios_analyser`` class

We can load a bios while intitializing the module ``bios_analyzer``, we then call the methods that applies directly on the loaded bios.

In [2]:
example_bios_1 = "je suis president du monde et journaliste chez sciencespo"

print('starting class bios analyzer...')
extractor = tpp.bios_analyzer(example_bios_1)

starting class bios analyzer...

In [3]:
# Example for full_tokenize function
print('tokenization')
extractor.full_tokenize()
print(extractor.full_tokens)

tokenization
['president', 'monde', 'journaliste', 'chez', 'sciencespo', ('president', 'monde'), ('monde', 'journaliste'), ('journaliste', 'chez'), ('chez', 'sciencespo')]

In [4]:
# For each get function we can get the estimation
print("profession extraction")

# directly as return of the function
print(extractor.get_professions())

# or as a class attribute
print(extractor.professions)

profession extraction
['journalist']
['journalist']

In [5]:
# For each get function we can get the estimation
print("statuses extraction")

# directly as return of the function
print(extractor.get_allstatuses())

# or as a class attribute
print(extractor.allstatuses)

statuses extraction
['sciencespo', 'president']
['sciencespo', 'president']

In [6]:
# For each get function we can get the estimation
print("language extraction")

# directly as return of the function
print(extractor.get_lang())

# or as a class attribute
print(extractor.language)

language extraction
fr
fr

## List of the methods

In [7]:
# tokenize method
tokens = extractor.tokenize()
print("tokens:", tokens)

# bi_tokenize method
bi_tokens = extractor.bi_tokenize()
print("bi_tokens:", bi_tokens)

# full_tokenize method
full_tokens = extractor.full_tokenize()
print("full_tokens:", full_tokens)

# get_actorstatuses method
actorstatuses = extractor.get_actorstatuses()
print("actorstatuses:", actorstatuses)

# get_ages method
ages = extractor.get_ages()
print("ages:", ages)

# get_allstatuses method
allstatuses = extractor.get_allstatuses()
print("allstatuses:", allstatuses)

# get_gender method
gender = extractor.get_gender()
print("gender:", gender)

# get_groupstatuses method
groupstatuses = extractor.get_groupstatuses()
print("groupstatuses:", groupstatuses)

# get_lang method
lang = extractor.get_lang()
print("lang:", lang)

# get_professions method
professions = extractor.get_professions()
print("professions:", professions)

# get_prostatus method
prostatus = extractor.get_prostatus()
print("prostatus:", prostatus)

# get_topics method
topics = extractor.get_topics()
print("topics:", topics)

# get_universitystatuses method
universitystatuses = extractor.get_universitystatuses()
print("universitystatuses:", universitystatuses)

tokens: ['president', 'monde', 'journaliste', 'chez', 'sciencespo']
bi_tokens: [('president', 'monde'), ('monde', 'journaliste'), ('journaliste', 'chez'), ('chez', 'sciencespo')]
full_tokens: ['president', 'monde', 'journaliste', 'chez', 'sciencespo', ('president', 'monde'), ('monde', 'journaliste'), ('journaliste', 'chez'), ('chez', 'sciencespo')]
actorstatuses: []
ages: []
allstatuses: ['sciencespo', 'president']
gender: ['Man']
groupstatuses: []
lang: fr
professions: ['journalist']
prostatus: ['president']
topics: []
universitystatuses: ['sciencespo']

## Method 2 : direct function

In this method we want to use the module on other bios and not on the one loaded in the module. We just need to add an argument `bios` to our methods.

In [8]:
example_bios_1 = "je suis president du monde et journaliste chez sciencespo"
example_bios_2 = "Software Developer at Microsoft, passionate about AI and cloud computing"

print('starting class')
extractor = tpp.bios_analyzer()

starting class

In [9]:
print(extractor.get_professions(bios=example_bios_1))
print(extractor.get_professions(bios=example_bios_2))

['journalist']
['developer']

## Method 3 : automatically process dataframe

We build a class ``df_bios_analyzer`` meant to process directly your dataframe.

In [10]:
import pandas as pd

# create a dataframe with sample data
df = pd.DataFrame({
    'id': [1, 2, 3],
    'description': [
        'je suis president du monde et journaliste chez sciencespo',
        'software engineer at Google, love to travel',
        'CEO at startup, passionate about AI and machine learning'
    ]
})
df

   id                                        description
0   1  je suis president du monde et journaliste chez...
1   2        software engineer at Google, love to travel
2   3  CEO at startup, passionate about AI and machin...

In [11]:
df_extractor = tpp.df_bios_analyzer(df=df, description_column='description')

In [12]:
df_extractor.full_tokenize()
df_extractor.df

,id,description,full_tokens
0,1,je suis president du monde et journaliste chez...,"[president, monde, journaliste, chez, sciences..."
1,2,"software engineer at Google, love to travel","[software, engineer, google, love, travel, (so..."
2,3,"CEO at startup, passionate about AI and machin...","[ceo, startup, passionate, machine, learning, ..."

In [13]:
df_extractor.get_professions(tokens_column='full_tokens')	
df_extractor.df

,id,description,full_tokens,professions
0,1,je suis president du monde et journaliste chez...,"[president, monde, journaliste, chez, sciences...",[journalist]
1,2,"software engineer at Google, love to travel","[software, engineer, google, love, travel, (so...","[engineer, developer]"
2,3,"CEO at startup, passionate about AI and machin...","[ceo, startup, passionate, machine, learning, ...",[ceo]

We can also apply all the columns together using get_all

In [14]:
df_extractor.get_all()

,id,description,full_tokens,professions,tokens,bi_tokens,prostatus,actorstatus,groupstatus,universitystatus,allstatus,age,gender,topic,lang
0,1,je suis president du monde et journaliste chez...,"[president, monde, journaliste, chez, sciences...",[journalist],"[president, monde, journaliste, chez, sciencespo]","[(president, monde), (monde, journaliste), (jo...",[president],[],[],[sciencespo],"[sciencespo, president]",[],[Man],[],fr
1,2,"software engineer at Google, love to travel","[software, engineer, google, love, travel, (so...","[engineer, developer]","[software, engineer, google, love, travel]","[(software, engineer), (engineer, google), (go...",[],[],[],[],[],[],[],[],en
2,3,"CEO at startup, passionate about AI and machin...","[ceo, startup, passionate, machine, learning, ...",[ceo],"[ceo, startup, passionate, machine, learning]","[(ceo, startup), (startup, passionate), (passi...",[],[startup],[],[],[startup],[],[],[entrepreneurship],en

# Get keywords

If you want to access the full list of keywords you can do this :

In [15]:
tpp.get_pro_kewords()

,Sum,Keywords,Group
Professions,,,
journalist,1362,"journaliste, reporter, journalist, pigiste, ex...","Information, arts and entertainment professions"
author,456,"auteur, créateur, writer, chroniqueur, author,...","Information, arts and entertainment professions"
professor,425,"prof, professeur, enseignant, formateur, profe...",Professors and higher scientific professions
city ​​councilor,335,"('conseiller', 'municipal'), ('conseillère', '...",Elected officers and political representatives
ceo,333,"ceo, dg, pdg, ('directeur', 'général'), ('chef...","Business, IT and administration professionals"
mayor,311,maire,Elected officers and political representatives
consultant,284,"consultant, consultante, consulting, ('cabinet...","Business, IT and administration professionals"
editor,226,"rédacteur, rédactrice, editor, éditeur, ('red'...","Information, arts and entertainment professions"
attorney,225,"avocat, barreau, avocate, lawyer, advocate",Legal professions
entrepreneur,220,"entrepreneur, entrepreneure","Business, IT and administration professionals"
deputy mayor,167,"maireadjoint, ('adjoint', 'maire'), ('adjointe...",Elected officers and political representatives
engineer,165,"ingénieur, ingenieur, ingénieure, ingenieure, ...","Business, IT and administration professionals"
communications manager,126,"('responsable', 'communication'), ('chargée', ...","Business, IT and administration professionals"
regional councilor,121,"('conseiller', 'régional'), ('conseillère', 'r...",Elected officers and political representatives
animator,119,"animateur, animatrice, présentateur, présentat...","Information, arts and entertainment professions"
departmental councilor,113,"('conseiller', 'départemental'), ('conseil', '...",Elected officers and political representatives
researcher,108,"chercheur, chercheuse , doctorant, doctorante,...",Professors and higher scientific professions
human resources,106,"rh, ('ressources', 'humaines')","Business, IT and administration professionals"
project manager,86,"('chef', 'service'), ('chef', 'projet'), ('pro...","Business, IT and administration professionals"
member of parliament,83,"député, députée",Elected officers and political representatives
lawyer,81,juriste,Legal professions
artist,80,"artiste, peintre, artist","Information, arts and entertainment professions"
parliamentarian,72,parlementaire,Elected officers and political representatives
coach,69,"coach, coaching","Business, IT and administration professionals"
physician,66,médecin,Other
analyst,63,"analyst, analyste, ('data', 'scientist')","Business, IT and administration professionals"
actor,60,"acteur, comédien, comedien, comédiennne, comed...","Information, arts and entertainment professions"
photographer,58,photographe,"Information, arts and entertainment professions"
developer,56,"développeur, developpeur, développeuse, develo...","Business, IT and administration professionals"
farmer,52,"agriculteur, éleveur",Other
mission manager,46,"('chargé', 'mission'), ('chargée', 'mission')","Business, IT and administration professionals"
national councilor,46,"('conseil', 'national'), ('conseiller', 'natio...",Elected officers and political representatives
producer,41,producteur,"Information, arts and entertainment professions"
blogger,41,"blogueur, blogueuse","Information, arts and entertainment professions"
nurse,40,"infirmier, infirmière",Other
film director,39,"réalisateur, réalisatrice","Information, arts and entertainment professions"
parliamentary collaborator,38,"('collaborateur', 'parlementaire'), ('collabor...",Elected officers and political representatives
designer,35,"designer, concepteur","Business, IT and administration professionals"
accountant,34,"comptable, expertcomptable","Business, IT and administration professionals"
architect,32,architecte,Other
minister,29,ministre,Elected officers and political representatives
firefighter,26,"pompier, sapeurpompier",Other
public service,26,"('fonction', 'publique'), ('service', 'public')",Elected officers and political representatives
philosopher,20,philosophe,Professors and higher scientific professions
historian,20,"historien, historienne",Professors and higher scientific professions
artisan,16,artisan,Other
community manager,16,"('community', 'manager')","Business, IT and administration professionals"
economist,15,economiste,Professors and higher scientific professions
sociologist,15,sociologue,Professors and higher scientific professions
psychologist,14,psychologue,Professors and higher scientific professions
mediator,14,"médiateur, mediateur, mediatrice, médiatrice",Other
hunter,11,chasseur,Other

In [16]:
tpp.get_status_kewords()

,Sum,Keywords,Type,Age
Status,,,,
former,904,"ex, ancien, ancienne, exjournaliste, exprésident",professional,NaN
director,829,"directeur, directrice, director, head, directi...",professional,NaN
advisor,734,"conseiller, conseillère, advisor, ('ancien', '...",professional,NaN
president,695,"président, présidente, president, presidente",professional,NaN
executive,539,"responsable, manager, cadre",professional,NaN
activist,503,"militant, engagé, engagée, militante, engageme...",groupe,NaN
founder,454,"fondateur, founder, cofondateur, cofounder, fo...",professional,NaN
enthusiast,447,"passionné, passionnée, amateur, amatrice, enth...",professional,NaN
member,405,"membre, member, adhérent",professional,NaN
chief,370,"chef, cheffe",professional,NaN
association,327,"association, lassociation, asso, associatif, ong",actor_type,NaN
citizen,309,"citoyen, citoyenne, citizen",groupe,NaN
assistant,306,"adjoint, adjointe, assistant, assistante",professional,NaN
official account,297,"('compte', 'officiel'), ('twitter', 'officiel'...",actor_type,NaN
student,269,"étudiant, student, etudiant, étudiante, etudiante",professional,Young
personal account,247,"('compte', 'personnel'), ('compte', 'perso'), ...",actor_type,NaN
university,239,"université, institut, école, ecole, university...",actor_type,NaN
delegate,215,"délégué, déléguée",professional,NaN
alumni,197,"alumni, diplômé, diplômée, 🎓, alumnus",professional,NaN
candidate,192,"candidat, candidate",professional,NaN
vice-president,186,"viceprésident, viceprésidente, ('vice', 'prési...",professional,NaN
support,175,"soutien, ('compte', 'soutien'), ('comité', 'so...",groupe,NaN
professional,174,"pro, professionnel, professionnelle, professional",professional,NaN
media,174,"media, média, ('media', 'digital')",actor_type,NaN
specialist,166,"spécialiste, spécialisée, spécialisé, specialist",professional,NaN
independent,159,"indépendant, freelance, indépendante",professional,NaN
fan,158,fan,groupe,NaN
sciencespo,151,"sciencespo, ('sciences', 'po')",affiliation,NaN
elected,143,"élu, élue, elu",professional,NaN
committee,137,"comité, commission",actor_type,NaN
federation,125,fédération,actor_type,NaN
agency,112,"agence, agency",actor_type,NaN
startup,111,startup,actor_type,NaN
entreprise,104,entreprise,actor_type,NaN
phd,103,"phd, doctorant, doctorante",professional,NaN
retired,102,"retraité, retraitée",professional,Old
expert,101,"expert, experte",professional,NaN
important member,94,"('membre', 'bureau'), ('membre', 'conseil'), (...",professional,NaN
union,82,syndicat,actor_type,NaN
junior,69,"jeune, junior",professional,Young
general secretary,69,"('secrétaire', 'général'), ('secrétaire', 'gén...",professional,NaN
amdassador,68,"ambassadeur, ambassador, ambassadrice",professional,NaN
senior,66,"senior, vieux",professional,Old
collaborator,57,"collaborateur, collaboratrice",professional,NaN
administrator,53,administrateur,professional,NaN
sorbonne,53,"sorbonneparis1, sorbonne",affiliation,NaN
coordinator,52,"coordinateur, coordinatrice",professional,NaN
foundation,51,fondation,actor_type,NaN
doctor,49,"docteur, docteure",professional,NaN
board of directors,47,"ca, ('conseil', 'dadministration')",actor_type,NaN
city ​​hall,44,mairie,actor_type,NaN
mine,36,mine,affiliation,NaN
volunteer,36,bénévole,groupe,NaN
deputy director,30,"('directeur', 'adjoint'), ('directeur', 'assoc...",professional,NaN
apprentice,28,"apprenti, apprentissage",professional,NaN
think tank,27,"('think', 'tank')",actor_type,NaN
master,26,maître,professional,NaN
technician,13,"technicien, technicienne",professional,NaN
worker,11,travailleur,professional,NaN
thinker,11,penseur,personal,NaN

In [17]:
tpp.get_gender_kewords()

         Sum                                           Keywords
Gender
Man     5514  président, conseiller, directeur, chef, passio...
Woman   2053  conseillère, directrice, ingénieure, ingenieur...

In [18]:
tpp.get_topic_kewords()

,Sum,Keywords
Topics,,
politics,1144,"politique, politiques, politics, policy, polit..."
digital,810,"digital, numérique, internet, informatique, di..."
communication,616,"communication, communications, compublique"
culture,616,"culture, cinéma, patrimoine, arts, théâtre, cu..."
public,464,"public, publique, publiques, servicepublic, af..."
innovation,451,"innovation, linnovation, ('digital', 'innovati..."
law,432,"droit, droits, juridique, ('droit', 'public')"
education,375,"formation, education, éducation, études"
technology,362,"tech, technologies, frenchtech, technology, fi..."
sciences,301,"sciences, science, scientifique, maths, mathém..."
health,282,"santé, health, médecine"
business,282,"business, commerce, ecommerce, commercial"
research,265,"recherche, phd, research, chercheur, chercheuse"
marketing,259,"marketing, webmarketing, publicité, digitalmar..."
development,247,"développement, development, ('développement', ..."
music,244,"musique, music, musiques"
management,239,"management, gestion"
economy,234,"économie, economie, léconomie, economy, économ..."
biodiversity and environment,232,"environnement, biodiversité, environment, lenv..."
ecology,214,"écologie, ecologie, écologique, écolo, lécolog..."
security,213,"défense, sécurité, security, defense, ('marine..."
entrepreneurship,200,"startup, entrepreneurs, entrepreneuriat, entre..."
data,198,"data, ia, bigdata, opendata"
history,193,"histoire, dhistoire, lhistoire"
finance,184,"finance, banque, assurance, finances, financière"
press,171,presse
energy,170,"energy, energie, énergie, énergies, transition..."
justice,160,"justice, law, avocats"
agriculture,158,"agriculture, agricole, agriculteurs"
recruitment,152,"rh, recrutement, ('ressources', 'humaines')"
social medias,119,"socialmedia, ('réseaux', 'sociaux'), ('social'..."
strategy,113,"stratégie, strategy"
climate,94,"climat, climate"
real estate,92,immobilier
construction,81,"construction, urbanisme"
tourism,80,tourisme
sustainability,74,"sustainability, ('développement', 'durable'), ..."
literature,72,"littérature, ('lettres', 'modernes')"
mobility,57,mobilité
diplomacy,51,"diplomatie, ('relations', 'internationales'), ..."
agri-food,42,"agroalimentaire, alimentation"
design,41,design
philosophy,40,philosophie
sociology,23,sociologie
engineering,17,ingénierie